modLoader="javafml"
loaderVersion="[26,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/item-filters/issues"

[[mods]]
    modId="item_filters"
    version="1.0"
    displayName="Item Filters"
	authors="ManApart"
    description='''
    Hopper like item that will take only the items in its gui screen
    '''
    credits="Filter your items"

[[dependencies.item_filters]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"